apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- svc.yaml
- db-deployment.yaml
- db-svc-deployment.yaml
- result-deployment.yaml
- result-svc-deployment.yaml
- worker.yaml
